min_fastlane_version("2.73.0")

default_platform(:ios)

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    setup_circle_ci
    cocoapods
    # cocoapods
  end

  desc "Submit a new Beta Build to Fabric"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    match(type: "adhoc")
    gym(
      scheme: "circleci-example",
      export_method: "ad-hoc"
    )
    crashlytics(api_token: "44ec49ba9b9b21b2295485e493da59aefcff8992",
              build_secret: "dc4c33aed6fe70b29709550bca3e276253685d0a7204fafede9be49941ebdb51")
    #slack(
    #   message: "Successfully deployed new App Update."
    # )
  end
end
